/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MinecraftGround.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MinecraftGround: THREE.Mesh
  }
  materials: {
    minecraft_forest_ground: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/MinecraftGround.glb') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.MinecraftGround.geometry}
        material={materials.minecraft_forest_ground}
      />
    </group>
  )
}

useGLTF.preload('/MinecraftGround.glb')
