version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moko-xta-front-end
    ports:
      - '3000:80'
    volumes:
      - .:/app
      - /app/node_modules