/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LogoSpringBoot.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    LogoSpringBoot_1: THREE.Mesh
    LogoSpringBoot_2: THREE.Mesh
  }
  materials: {
    ['logo_spring_boot_#68bd45']: THREE.MeshStandardMaterial
    ['logo_spring_boot_#ffffff']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LogoSpringBoot.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LogoSpringBoot_1.geometry} material={materials['logo_spring_boot_#68bd45']} />
      <mesh geometry={nodes.LogoSpringBoot_2.geometry} material={materials['logo_spring_boot_#ffffff']} />
    </group>
  )
}

useGLTF.preload('/LogoSpringBoot.gltf')
