/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LogoNextjs.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LogoNextjs.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LogoNextjs.geometry} material={nodes.LogoNextjs.material} />
    </group>
  )
}

useGLTF.preload('/LogoNextjs.gltf')
