/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LogoPhotoshopColored.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    IconPhotoshop_1: THREE.Mesh
    IconPhotoshop_2: THREE.Mesh
  }
  materials: {
    ['icon_photoshop_#051e37']: THREE.MeshStandardMaterial
    ['icon_photoshop_#39a9ff']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/LogoPhotoshopColored.gltf',
  ) as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.IconPhotoshop_1.geometry}
        material={materials['icon_photoshop_#051e37']}
      />
      <mesh
        geometry={nodes.IconPhotoshop_2.geometry}
        material={materials['icon_photoshop_#39a9ff']}
      />
    </group>
  )
}

useGLTF.preload('/LogoPhotoshopColored.gltf')
