/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Nextjs.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GroupProps } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Nextjs_1: THREE.Mesh
    Nextjs_2: THREE.Mesh
  }
  materials: {
    background: THREE.MeshStandardMaterial
    image: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: GroupProps) {
  const { nodes, materials } = useGLTF('/Nextjs.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Nextjs_1.geometry}
        material={materials.background}
      />
      <mesh
        geometry={nodes.Nextjs_2.geometry}
        material={materials.image}
      />
    </group>
  )
}

useGLTF.preload('/Nextjs.gltf')
