/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HeliumBalloonO.glb --types -k 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    HeliumBalloonO: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/HeliumBalloonO.glb') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        name='HeliumBalloonO'
        geometry={nodes.HeliumBalloonO.geometry}
        material={nodes.HeliumBalloonO.material}
      />
    </group>
  )
}

useGLTF.preload('/HeliumBalloonO.glb')
