/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HeliumBalloonM.glb --types -k 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    HeliumBalloonM: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/HeliumBalloonM.glb') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        name='HeliumBalloonM'
        geometry={nodes.HeliumBalloonM.geometry}
        material={nodes.HeliumBalloonM.material}
      />
    </group>
  )
}

useGLTF.preload('/HeliumBalloonM.glb')
