/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LogoNextjs.glb --types -k 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    LogoNextjs_1: THREE.Mesh
    LogoNextjs_2: THREE.Mesh
  }
  materials: {
    ['logo_nextjs_simple_#000000']: THREE.MeshStandardMaterial
    ['logo_nextjs_simple_#ffffff']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LogoNextjs.glb') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        name='LogoNextjs_1'
        geometry={nodes.LogoNextjs_1.geometry}
        material={materials['logo_nextjs_simple_#000000']}
      />
      <mesh
        name='LogoNextjs_2'
        geometry={nodes.LogoNextjs_2.geometry}
        material={materials['logo_nextjs_simple_#ffffff']}
      />
    </group>
  )
}

useGLTF.preload('/LogoNextjs.glb')
