/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Smiley.glb --types -k 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Smiley: THREE.Mesh
  }
  materials: {
    smiley: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Smiley.glb') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        name='Smiley'
        geometry={nodes.Smiley.geometry}
        material={materials.smiley}
      />
    </group>
  )
}

useGLTF.preload('/Smiley.glb')
