/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Trinity.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Trinity_1: THREE.Mesh
    Trinity_2: THREE.Mesh
  }
  materials: {
    ['Gold.002']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Trinity.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Trinity_1.geometry}
        material={materials['Gold.002']}
      />
      <mesh
        geometry={nodes.Trinity_2.geometry}
        material={materials['Material.012']}
      />
    </group>
  )
}

useGLTF.preload('/Trinity.gltf')
