/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 DoorHandle.gltf --types -k 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    DoorHandle_1: THREE.Mesh
    DoorHandle_2: THREE.Mesh
  }
  materials: {
    door_handle: THREE.MeshStandardMaterial
    door_handle_ring: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/DoorHandle.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <group
        name='DoorHandle'
        position={[-28.6, 0, -10]}
      >
        <mesh
          name='DoorHandle_1'
          geometry={nodes.DoorHandle_1.geometry}
          material={materials.door_handle}
        />
        <mesh
          name='DoorHandle_2'
          geometry={nodes.DoorHandle_2.geometry}
          material={materials.door_handle_ring}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/DoorHandle.gltf')
