/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 SnakeCellStraight.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SnakeCellStraight_1: THREE.Mesh
    SnakeCellStraight_2: THREE.Mesh
    SnakeCellStraight_3: THREE.Mesh
    SnakeCellStraight_4: THREE.Mesh
    SnakeCellStraight_5: THREE.Mesh
    SnakeCellStraight_6: THREE.Mesh
    SnakeCellStraight_7: THREE.Mesh
    SnakeCellStraight_8: THREE.Mesh
    SnakeCellStraight_9: THREE.Mesh
    SnakeCellStraight_10: THREE.Mesh
  }
  materials: {
    snake_green_M: THREE.MeshStandardMaterial
    snake_green_XL: THREE.MeshStandardMaterial
    snake_green_XD: THREE.MeshStandardMaterial
    snake_green_D: THREE.MeshStandardMaterial
    snake_green_L: THREE.MeshStandardMaterial
    snake_yellow_XL: THREE.MeshStandardMaterial
    snake_yellow_XD: THREE.MeshStandardMaterial
    snake_yellow_D: THREE.MeshStandardMaterial
    snake_yellow_M: THREE.MeshStandardMaterial
    snake_yellow_L: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SnakeCellStraight.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SnakeCellStraight_1.geometry} material={materials.snake_green_M} />
      <mesh geometry={nodes.SnakeCellStraight_2.geometry} material={materials.snake_green_XL} />
      <mesh geometry={nodes.SnakeCellStraight_3.geometry} material={materials.snake_green_XD} />
      <mesh geometry={nodes.SnakeCellStraight_4.geometry} material={materials.snake_green_D} />
      <mesh geometry={nodes.SnakeCellStraight_5.geometry} material={materials.snake_green_L} />
      <mesh geometry={nodes.SnakeCellStraight_6.geometry} material={materials.snake_yellow_XL} />
      <mesh geometry={nodes.SnakeCellStraight_7.geometry} material={materials.snake_yellow_XD} />
      <mesh geometry={nodes.SnakeCellStraight_8.geometry} material={materials.snake_yellow_D} />
      <mesh geometry={nodes.SnakeCellStraight_9.geometry} material={materials.snake_yellow_M} />
      <mesh geometry={nodes.SnakeCellStraight_10.geometry} material={materials.snake_yellow_L} />
    </group>
  )
}

useGLTF.preload('/SnakeCellStraight.gltf')
