/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LogoGit.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    LogoGit: THREE.Mesh
  }
  materials: {
    ['logo_git_material_#F03C2DFF']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LogoGit.glb') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.LogoGit.geometry}
        material={materials['logo_git_material_#F03C2DFF']}
      />
    </group>
  )
}

useGLTF.preload('/LogoGit.glb')
