/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 OwlSticker.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    OwlSticker_1: THREE.Mesh
    OwlSticker_2: THREE.Mesh
    OwlSticker_3: THREE.Mesh
  }
  materials: {
    ['glitter_sticher_002.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/OwlSticker.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.OwlSticker_1.geometry}
        material={materials['glitter_sticher_002.002']}
      />
      <mesh
        geometry={nodes.OwlSticker_2.geometry}
        material={materials['Material.004']}
      />
      <mesh
        geometry={nodes.OwlSticker_3.geometry}
        material={materials.white}
      />
    </group>
  )
}

useGLTF.preload('/OwlSticker.gltf')
