/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MacBookPro.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MacBookPro_1: THREE.Mesh
    MacBookPro_2: THREE.Mesh
    MacBookPro_3: THREE.Mesh
  }
  materials: {
    mac_book_pro: THREE.MeshStandardMaterial
    mac_book_pro_screen: THREE.MeshStandardMaterial
    mac_book_pro_keyboard: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/MacBookPro.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 9.182, -8]}>
        <mesh geometry={nodes.MacBookPro_1.geometry} material={materials.mac_book_pro} />
        <mesh geometry={nodes.MacBookPro_2.geometry} material={materials.mac_book_pro_screen} />
        <mesh geometry={nodes.MacBookPro_3.geometry} material={materials.mac_book_pro_keyboard} />
      </group>
    </group>
  )
}

useGLTF.preload('/MacBookPro.glb')
