/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Laboratoire.gltf --types -k 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TrestleLeft: THREE.Mesh
    TrestleRight: THREE.Mesh
    MacBookPro: THREE.Mesh
    Screen: THREE.Mesh
    NotebookTop: THREE.Mesh
    NotebookBottom: THREE.Mesh
    DeskChair: THREE.Mesh
    TransfertBoxes001: THREE.Mesh
    TransfertBoxes002: THREE.Mesh
    TransfertBoxes003: THREE.Mesh
    VinylDisc: THREE.Mesh
    DoorHandle: THREE.Mesh
    Door: THREE.Mesh
    DoorFrame: THREE.Mesh
    TableLamp: THREE.Mesh
    CeilingLampFrame: THREE.Mesh
    CeilingLamp: THREE.Mesh
    Parquet: THREE.Mesh
    Shelf: THREE.Mesh
    VirgenDeGuadalupe: THREE.Mesh
    PabloEscobar: THREE.Mesh
    Tetrahedron: THREE.Mesh
    Cube: THREE.Mesh
    Dodecahedron: THREE.Mesh
    Octahedron: THREE.Mesh
    Icosahedron: THREE.Mesh
    SpeakerLeft: THREE.Mesh
    SpeakerRight: THREE.Mesh
    WorldMap: THREE.Mesh
    Ceiling: THREE.Mesh
    NorthWall: THREE.Mesh
    WestWall: THREE.Mesh
    PlinthNorth: THREE.Mesh
    PlinthWestLarge: THREE.Mesh
    PlinthWestSmall: THREE.Mesh
    VideoProjectorScreen: THREE.Mesh
    SecondHand: THREE.Mesh
    HourHand: THREE.Mesh
    MinuteHand: THREE.Mesh
    WallClockGlass: THREE.Mesh
    WallClock: THREE.Mesh
    HourAndMinuteMarkers: THREE.Mesh
    AmorLlamaAmor: THREE.Mesh
    Brain: THREE.Mesh
    Trinity: THREE.Mesh
    Couronnes: THREE.Mesh
    NicotianaRustica: THREE.Mesh
    CelestialMap: THREE.Mesh
    VerbalShoota: THREE.Mesh
    FrameGlasses: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Laboratoire.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        name='TrestleLeft'
        geometry={nodes.TrestleLeft.geometry}
        material={nodes.TrestleLeft.material}
        position={[-7.5, 0.02, -10]}
      />
      <mesh
        name='TrestleRight'
        geometry={nodes.TrestleRight.geometry}
        material={nodes.TrestleRight.material}
        position={[7.5, 0.02, -10]}
      />
      <mesh
        name='MacBookPro'
        geometry={nodes.MacBookPro.geometry}
        material={nodes.MacBookPro.material}
        position={[0, 9.182, -8]}
      />
      <mesh
        name='Screen'
        geometry={nodes.Screen.geometry}
        material={nodes.Screen.material}
        position={[0, 9.182, -14.4]}
      />
      <mesh
        name='NotebookTop'
        geometry={nodes.NotebookTop.geometry}
        material={nodes.NotebookTop.material}
        position={[5.572, 9.222, -9.098]}
      />
      <mesh
        name='NotebookBottom'
        geometry={nodes.NotebookBottom.geometry}
        material={nodes.NotebookBottom.material}
        position={[5.772, 9.182, -8.898]}
      />
      <mesh
        name='DeskChair'
        geometry={nodes.DeskChair.geometry}
        material={nodes.DeskChair.material}
        position={[0, 0.02, 0]}
        rotation={[-Math.PI, 1.067, -Math.PI]}
      />
      <mesh
        name='TransfertBoxes001'
        geometry={nodes.TransfertBoxes001.geometry}
        material={nodes.TransfertBoxes001.material}
        position={[-6.441, 1.583, -11.819]}
        scale={1.2}
      />
      <mesh
        name='TransfertBoxes002'
        geometry={nodes.TransfertBoxes002.geometry}
        material={nodes.TransfertBoxes002.material}
        position={[-6.385, 1.583, -11.019]}
        rotation={[0, 0.047, 0]}
        scale={1.2}
      />
      <mesh
        name='TransfertBoxes003'
        geometry={nodes.TransfertBoxes003.geometry}
        material={nodes.TransfertBoxes003.material}
        position={[-6.528, 1.583, -10.035]}
        rotation={[0, -0.043, 0]}
        scale={1.2}
      />
      <mesh
        name='VinylDisc'
        geometry={nodes.VinylDisc.geometry}
        material={nodes.VinylDisc.material}
        position={[7.5, 1.575, -7.45]}
      />
      <mesh
        name='DoorHandle'
        geometry={nodes.DoorHandle.geometry}
        material={nodes.DoorHandle.material}
        position={[-29, 0, -10]}
      />
      <mesh
        name='Door'
        geometry={nodes.Door.geometry}
        material={nodes.Door.material}
        position={[-29, 0, -10]}
      />
      <mesh
        name='DoorFrame'
        geometry={nodes.DoorFrame.geometry}
        material={nodes.DoorFrame.material}
        position={[-29, 0, -10]}
      />
      <mesh
        name='TableLamp'
        geometry={nodes.TableLamp.geometry}
        material={nodes.TableLamp.material}
        position={[11.776, 1.012, -9.08]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={1.618}
      />
      <mesh
        name='CeilingLampFrame'
        geometry={nodes.CeilingLampFrame.geometry}
        material={nodes.CeilingLampFrame.material}
        position={[0, 28.6, 0]}
      />
      <mesh
        name='CeilingLamp'
        geometry={nodes.CeilingLamp.geometry}
        material={nodes.CeilingLamp.material}
        position={[0, 28.6, 0]}
      />
      <mesh
        name='Parquet'
        geometry={nodes.Parquet.geometry}
        material={nodes.Parquet.material}
        position={[0, -0.158, 0]}
      />
      <mesh
        name='Shelf'
        geometry={nodes.Shelf.geometry}
        material={nodes.Shelf.material}
        position={[0, 18, -16]}
      />
      <mesh
        name='VirgenDeGuadalupe'
        geometry={nodes.VirgenDeGuadalupe.geometry}
        material={nodes.VirgenDeGuadalupe.material}
        position={[-4.512, 18.127, -15.546]}
      />
      <mesh
        name='PabloEscobar'
        geometry={nodes.PabloEscobar.geometry}
        material={nodes.PabloEscobar.material}
        position={[4.936, 18.127, -15.546]}
      />
      <mesh
        name='Tetrahedron'
        geometry={nodes.Tetrahedron.geometry}
        material={nodes.Tetrahedron.material}
        position={[4.034, 18.12, -15.305]}
      />
      <mesh
        name='Cube'
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[4.377, 18.12, -14.612]}
      />
      <mesh
        name='Dodecahedron'
        geometry={nodes.Dodecahedron.geometry}
        material={nodes.Dodecahedron.material}
        position={[3.82, 18.12, -14.48]}
      />
      <mesh
        name='Octahedron'
        geometry={nodes.Octahedron.geometry}
        material={nodes.Octahedron.material}
        position={[3.414, 18.12, -14.86]}
      />
      <mesh
        name='Icosahedron'
        geometry={nodes.Icosahedron.geometry}
        material={nodes.Icosahedron.material}
        position={[3.621, 18.12, -15.221]}
      />
      <mesh
        name='SpeakerLeft'
        geometry={nodes.SpeakerLeft.geometry}
        material={nodes.SpeakerLeft.material}
        position={[-12.275, 0, -14.251]}
      />
      <mesh
        name='SpeakerRight'
        geometry={nodes.SpeakerRight.geometry}
        material={nodes.SpeakerRight.material}
        position={[12.725, 0, -14.325]}
      />
      <mesh
        name='WorldMap'
        geometry={nodes.WorldMap.geometry}
        material={nodes.WorldMap.material}
        position={[-12.2, 10.333, -14.1]}
      />
      <mesh
        name='Ceiling'
        geometry={nodes.Ceiling.geometry}
        material={nodes.Ceiling.material}
        scale={[10, 8.938, 11.189]}
      />
      <mesh
        name='NorthWall'
        geometry={nodes.NorthWall.geometry}
        material={nodes.NorthWall.material}
      />
      <mesh
        name='WestWall'
        geometry={nodes.WestWall.geometry}
        material={nodes.WestWall.material}
      />
      <mesh
        name='PlinthNorth'
        geometry={nodes.PlinthNorth.geometry}
        material={nodes.PlinthNorth.material}
        position={[-28.6, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        name='PlinthWestLarge'
        geometry={nodes.PlinthWestLarge.geometry}
        material={nodes.PlinthWestLarge.material}
        position={[-28.6, 0, 16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        name='PlinthWestSmall'
        geometry={nodes.PlinthWestSmall.geometry}
        material={nodes.PlinthWestSmall.material}
        position={[-28.6, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        name='VideoProjectorScreen'
        geometry={nodes.VideoProjectorScreen.geometry}
        material={nodes.VideoProjectorScreen.material}
        position={[-28.6, 25, 5.5]}
      />
      <mesh
        name='SecondHand'
        geometry={nodes.SecondHand.geometry}
        material={nodes.SecondHand.material}
        position={[-28.331, 25.4, -10.007]}
        rotation={[-Math.PI / 4, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh
        name='HourHand'
        geometry={nodes.HourHand.geometry}
        material={nodes.HourHand.material}
        position={[-28.366, 25.4, -10.007]}
        rotation={[2.531, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh
        name='MinuteHand'
        geometry={nodes.MinuteHand.geometry}
        material={nodes.MinuteHand.material}
        position={[-28.345, 25.4, -10.007]}
        rotation={[0.698, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh
        name='WallClockGlass'
        geometry={nodes.WallClockGlass.geometry}
        material={nodes.WallClockGlass.material}
        position={[-28.583, 25.4, -10.007]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh
        name='WallClock'
        geometry={nodes.WallClock.geometry}
        material={nodes.WallClock.material}
        position={[-28.583, 25.4, -10.007]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh
        name='HourAndMinuteMarkers'
        geometry={nodes.HourAndMinuteMarkers.geometry}
        material={nodes.HourAndMinuteMarkers.material}
        position={[-28.372, 25.4, -10.007]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh
        name='AmorLlamaAmor'
        geometry={nodes.AmorLlamaAmor.geometry}
        material={nodes.AmorLlamaAmor.material}
        position={[-11.2, 10, -16]}
        scale={[0.99, 1, 1]}
      />
      <mesh
        name='Brain'
        geometry={nodes.Brain.geometry}
        material={nodes.Brain.material}
        position={[-19.06, 10, -16]}
      />
      <mesh
        name='Trinity'
        geometry={nodes.Trinity.geometry}
        material={nodes.Trinity.material}
        position={[-17.09, 19.2, -16]}
      />
      <mesh
        name='Couronnes'
        geometry={nodes.Couronnes.geometry}
        material={nodes.Couronnes.material}
        position={[0, 25.6, -16]}
      />
      <mesh
        name='NicotianaRustica'
        geometry={nodes.NicotianaRustica.geometry}
        material={nodes.NicotianaRustica.material}
        position={[10.2, 14.9, -16]}
      />
      <mesh
        name='CelestialMap'
        geometry={nodes.CelestialMap.geometry}
        material={nodes.CelestialMap.material}
        position={[10.1, 10.2, -16]}
      />
      <mesh
        name='VerbalShoota'
        geometry={nodes.VerbalShoota.geometry}
        material={nodes.VerbalShoota.material}
        position={[19.032, 14.9, -16]}
      />
      <mesh
        name='FrameGlasses'
        geometry={nodes.FrameGlasses.geometry}
        material={nodes.FrameGlasses.material}
        position={[-19.06, 10, -16]}
      />
    </group>
  )
}

useGLTF.preload('/Laboratoire.gltf')
