/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 MacBookPro.gltf --types -k 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MacBookPro_1: THREE.Mesh
    MacBookPro_2: THREE.Mesh
    MacBookPro_3: THREE.Mesh
  }
  materials: {
    mac_book_pro: THREE.MeshStandardMaterial
    mac_book_pro_screen: THREE.MeshStandardMaterial
    mac_book_pro_keyboard: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/MacBookPro.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <group
        name='MacBookPro'
        position={[0, 9.182, -8]}
      >
        <mesh
          name='MacBookPro_1'
          geometry={nodes.MacBookPro_1.geometry}
          material={materials.mac_book_pro}
        />
        <mesh
          name='MacBookPro_2'
          geometry={nodes.MacBookPro_2.geometry}
          material={materials.mac_book_pro_screen}
        />
        <mesh
          name='MacBookPro_3'
          geometry={nodes.MacBookPro_3.geometry}
          material={materials.mac_book_pro_keyboard}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/MacBookPro.gltf')
