/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 VinylDisc.gltf --types -k 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    VinylDisc_1: THREE.Mesh
    VinylDisc_2: THREE.Mesh
  }
  materials: {
    vinyl_disc_finira: THREE.MeshStandardMaterial
    vinyl_disc_back: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/VinylDisc.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        name='VinylDisc_1'
        geometry={nodes.VinylDisc_1.geometry}
        material={materials.vinyl_disc_finira}
      />
      <mesh
        name='VinylDisc_2'
        geometry={nodes.VinylDisc_2.geometry}
        material={materials.vinyl_disc_back}
      />
    </group>
  )
}

useGLTF.preload('/VinylDisc.gltf')
