/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 WallClock.gltf --types -k 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    WallClock_1: THREE.Mesh
    WallClock_2: THREE.Mesh
  }
  materials: {
    wall_clock_brushed_metal: THREE.MeshStandardMaterial
    mondaine_wall_clock: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/WallClock.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <group
        name='WallClock'
        position={[-28.583, 25.4, -10.007]}
      >
        <mesh
          name='WallClock_1'
          geometry={nodes.WallClock_1.geometry}
          material={materials.wall_clock_brushed_metal}
        />
        <mesh
          name='WallClock_2'
          geometry={nodes.WallClock_2.geometry}
          material={materials.mondaine_wall_clock}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/WallClock.gltf')
