/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 WorldMap.gltf --types -k 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    WorldMap: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/WorldMap.gltf') as GLTFResult
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        name='WorldMap'
        geometry={nodes.WorldMap.geometry}
        material={nodes.WorldMap.material}
        position={[-12.188, 12.685, -14.096]}
        rotation={[0, -Math.PI / 9, 0.262]}
      />
    </group>
  )
}

useGLTF.preload('/WorldMap.gltf')
