import type { Metadata } from 'next'
import { GoogleAnalytics } from '@next/third-parties/google'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import { ReactLenis } from 'lenis/react'

import ReduxProvider from '@/redux/ReduxProvider'

import Menu from '@/components/layout/menu'

import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: "Moco's portfolio - Federico Desmoulin",
  description: 'Generated by create next app', // TODO: Description
}

export default function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: {
    locale: string
  }
}>) {
  const translations = useMessages()
  // const gaId = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_MEASUREMENT_KEY

  return (
    <html lang={locale}>
      <head>

      </head>
      <ReactLenis
        root
        options={{
          lerp: 0.1,
          duration: 1.2,
          smoothWheel: true,
          touchMultiplier: 2,
        }}
      >
        <body>
          <ReduxProvider>
            <NextIntlClientProvider
              // locale={locale}
              messages={translations}
            >
              <Menu />
              {children}
            </NextIntlClientProvider>
          </ReduxProvider>
        </body>
      </ReactLenis>
      <GoogleAnalytics gaId="G-TN9SNWP2HB" />
    </html>
  )
}
