import type { Metadata } from 'next'
import { NextIntlClientProvider, useMessages } from 'next-intl'

import Header from '@/components/header'

import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: {
    locale: string
  }
}>) {
  const translations = useMessages()

  return (
    <html lang='en'>
      <body>
        <NextIntlClientProvider
          locale={locale}
          messages={translations}
        >
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
